### ISSUE TITLE
Why we use stdx.allocator.internal?

### ISSUE THREAD

**Issue by 9il** [dlang-community/stdx-allocator#14]
If we have any then I would move it to mir-core and add mir-core as a dependency.

**Comment by wilzbach** [comment]
Because `emplaceRef` is still not public in Phobos and this removed the dependency on `std.conv` entirely.

I'm aware of your [`std.backdoor`](https://github.com/libmir/mir-core/blob/master/source/std/backdoor.d) trick and it's a neat solution too (though it still requires `std.conv` from Phobos).

> If we have any then I would move it to mir-core and add mir-core as a dependency.

Sounds good to me too. When I split out the allocator from Phobos the main reason for the internal module was that std.conv changed over multiple DMD versions so one couldn't depend on it.

**Comment by 9il** [comment]
Thanks!
