### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by 9il** [dlang-community/stdx-allocator#17]

**Comment by wilzbach** [comment]
https://github.com/dlang-community/stdx-allocator/releases/tag/v3.0.0

Though feel free to tag releases yourself.

**Comment by ghost** [comment]
The implicit dependence to mir was not mentioned (no changelog). I had seen it before that the very first PR was merged but i think that none of the dlang community soft will require the update to stdx alloc 3.x. The problem is that it adds a dependencies to mir (which then means adding again a submodule to each project).

Eventually a version could have been added (so for `max` and `emplace` if i've followed correctly) so that phobos can be used in projects that are not betterC stuff.

**Comment by 9il** [comment]
> The implicit dependence to mir was not mentioned (no changelog). I had seen it before that the very first PR was merged but i think that none of the dlang community soft will require the update to stdx alloc 3.x. The problem is that it adds a dependencies to mir (which then means adding again a submodule to each project).

Why a submodule would be required? Do we use something except dub/meson?

**Comment by 9il** [comment]
btw, meson update https://github.com/dlang-community/stdx-allocator/pull/18

**Comment by ghost** [comment]
> Do we use something except dub/meson?

Yes, DCD, D-Scanner, dfmt are all built with make and the git submodules (historically) then DUB support was added and then Meson. If at some point the stdx alloc git submodule of these products is pulled to v3.x.y then we'll have to add a submodule for mir-core.

Most likely this won't be a problem since they use only theAllocator and Mallocator there's no reason to update the revision that's used by their core libraries such as dparse, dsymbol, libdoc.
